spring:
  application:
    name: blog-other
  # 测试时，控制台彩色日志
  output:
    ansi:
      enabled: always
# mybatis-plus 相关配置
mybatis-plus:
  type-aliases-package: com.jxkj.managecenter
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # mybatis 原生配置
  configuration:
    #mybatis-plus配置控制台打印完整带参数SQL语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false

# 分布式事务
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: dscn-seata-group
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.109.135:8848
      namespace: f77491f9-7905-4f2e-913a-07546c4ad128
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.109.135:8848
      application: seata-server
      namespace: f77491f9-7905-4f2e-913a-07546c4ad128