spring:
  application:
    name: user-center
  # 测试时，控制台彩色日志
  output:
    ansi:
      enabled: always

# mybatis-plus 相关配置
mybatis-plus:
  type-aliases-package: com.jxkj.usercenter
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
  # mybatis 原生配置
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
swagger2:
  enable: true

#  seata:
#    enabled: true
#    application-id: ${spring.application.name}
#    tx-service-group: dscn-seata-group
#    config:
#      type: nacos
#      nacos:
#        serverAddr: 192.168.109.135:8848
#        namespace:
#        group: SEATA_GROUP
#        userName: ""
#        password: ""
#    registry:
#      type: nacos
#      nacos:
#        server-addr: 192.168.109.135:8848
#        application: seata-server
#        userName: ""
#        password: ""
#        namespace:
# 消费者将去访问微服务的名称
service-url:
  nacos-user-service: http://blog-center
