spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: db_user_center
    password: db_user_center
    url: jdbc:mysql://39.100.24.145/db_user_center?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  # 测试时，控制台彩色日志
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
# mybatis-plus 相关配置
mybatis-plus:
  type-aliases-package: com.jxkj.usercenter
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
  # mybatis 原生配置
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
swagger2:
  enable: true

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: dscn-seata-group
  config:
    type: nacos
    nacos:
      serverAddr: 123.57.26.161:8848
      namespace:
      group: SEATA_GROUP
      userName: ""
      password: ""
  registry:
    type: nacos
    nacos:
      server-addr: 123.57.26.161:8848
      application: seata-server
      userName: ""
      password: ""
      namespace:
# 消费者将去访问微服务的名称
service-url:
  nacos-user-service: http://blog-center
