spring:
  application:
    name: blog-resource
  cloud:
    nacos:
      discovery:
        server-addr: 39.100.24.145:5180
      config:
        # 配置中心的地址
        server-addr: 39.100.24.145:5180
        # 指定配置文件格式，相当于gitee上的那个文件
        file-extension: yaml
        # 分组
        group: DEFAULT_GROUP
        # 命名空间
        namespace: 2058def3-685a-4ca9-9c36-4729e5d2198a