spring:
  # 碰到重名bean 可以使用这个允许其覆盖
  main:
    allow-bean-definition-overriding: true
  application:
    name: blog-center
  # 测试时，控制台彩色日志
  output:
    ansi:
      enabled: always
# mybatis-plus 相关配置
mybatis-plus:
  type-aliases-package: com.jxkj.managecenter
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # mybatis-plus 的全局配置
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # mybatis 原生配置
  configuration:
    #mybatis-plus配置控制台打印完整带参数SQL语句
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false

# 消费者将去访问微服务的名称
service-url:
  nacos-user-service: http://user-center

ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
swagger2:
  enable: true
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: dscn-seata-group
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.109.135:8848
      namespace: f77491f9-7905-4f2e-913a-07546c4ad128
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.109.135:8848
      application: seata-server
      namespace: f77491f9-7905-4f2e-913a-07546c4ad128
server:
  port: 5220
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: db_user_center
#    password: db_user_center
#    url: jdbc:mysql://39.100.24.145/db_user_center?serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver